<a href="https://colab.research.google.com/github/Nailloon/Machine-Learning-Practice/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D0%AE%D0%B4%D0%B8%D0%BD%D1%86%D0%B5%D0%B2%D0%BE%D0%B9%20%D0%9D%D0%B0%D0%B4%D0%B5%D0%B6%D0%B4%D1%8B/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D1%8C%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Задание 1

классификация

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
data1 = pd.read_csv('/content/drive/MyDrive/diabetes.csv')
data1

,Unnamed: 0,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249044,249044,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
249045,249045,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
249046,249046,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
249047,249047,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
249048,249048,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
data1.drop(columns = ["Unnamed: 0"], inplace=True)

In [ ]:
data1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249044,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
249045,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
249046,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
249047,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
249048,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
data1 = data1.loc[data1['Diabetes_012'] != 1]
data1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
data1 = data1.replace({'Diabetes_012':{2:1}})
data1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
data1.to_csv('/content/drive/MyDrive/diabetes.csv')

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
y1 = data1["Diabetes_012"]
X1 = data1.drop(["Diabetes_012"], axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X1_train)
X1_train = scaler.transform(X1_train)
X1_test = scaler.transform(X1_test)

In [ ]:
from imblearn.under_sampling import RandomUnderSampler
undersampler = RandomUnderSampler()
X1_train, y1_train = undersampler.fit_resample(X1_train, y1_train)

In [ ]:
clf = DecisionTreeClassifier(max_depth=3)
clf.fit(X1_train, y1_train)

DecisionTreeClassifier(max_depth=3)

In [ ]:
pred1 = clf.predict(X1_test)
print(pred1)

[1. 1. 0. ... 1. 0. 0.]

In [ ]:

print(clf.score(X1_test, y1_test))

0.6103192130094358

In [ ]:
from sklearn import tree

text_representation = tree.export_text(clf)
print(text_representation)

|--- feature_0 <= 0.15
|   |--- feature_13 <= -0.00
|   |   |--- feature_18 <= 0.49
|   |   |   |--- class: 0.0
|   |   |--- feature_18 >  0.49
|   |   |   |--- class: 0.0
|   |--- feature_13 >  -0.00
|   |   |--- feature_18 <= -0.82
|   |   |   |--- class: 0.0
|   |   |--- feature_18 >  -0.82
|   |   |   |--- class: 1.0
|--- feature_0 >  0.15
|   |--- feature_13 <= -0.00
|   |   |--- feature_3 <= -0.13
|   |   |   |--- class: 0.0
|   |   |--- feature_3 >  -0.13
|   |   |   |--- class: 1.0
|   |--- feature_13 >  -0.00
|   |   |--- feature_3 <= -0.13
|   |   |   |--- class: 1.0
|   |   |--- feature_3 >  -0.13
|   |   |   |--- class: 1.0

регрессия

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
data2 = pd.read_csv('/content/drive/MyDrive/cars2.csv', index_col= False)
data2

,Unnamed: 0,odometer_value,year_produced,engine_has_gas,engine_capacity,has_warranty,price_usd,is_exchangeable,number_of_photos,up_counter,...,state_owned,drivetrain_all,drivetrain_front,drivetrain_rear,location_region_Брестская обл.,location_region_Витебская обл.,location_region_Гомельская обл.,location_region_Гродненская обл.,location_region_Минская обл.,location_region_Могилевская обл.
0,0,190000,2010,0,2.5,0,10900.00,0,9,13,...,1,1,0,0,0,0,0,0,1,0
1,1,290000,2002,0,3.0,0,5000.00,1,12,54,...,1,1,0,0,0,0,0,0,1,0
2,2,402000,2001,0,2.5,0,2800.00,1,4,72,...,1,1,0,0,0,0,0,0,1,0
3,3,10000,1999,0,3.0,0,9999.00,1,9,42,...,1,1,0,0,0,0,0,0,1,0
4,4,280000,2001,0,2.5,0,2134.11,1,14,7,...,1,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,38526,290000,2000,0,3.5,0,2750.00,1,5,85,...,1,0,1,0,0,0,0,0,1,0
38527,38527,321000,2004,0,2.2,0,4800.00,1,4,20,...,1,0,1,0,1,0,0,0,0,0
38528,38528,777957,2000,0,3.5,0,4300.00,0,3,63,...,1,0,1,0,0,0,0,0,1,0
38529,38529,20000,2001,0,2.0,0,4000.00,1,7,156,...,1,0,1,0,1,0,0,0,0,0
38530,38530,297729,2000,0,2.4,0,3200.00,1,4,73,...,1,0,1,0,0,0,0,0,1,0

In [ ]:
data2.drop(['Unnamed: 0'], axis=1)
data2.to_csv('/content/drive/MyDrive/cars3.csv', index= False)

In [ ]:
y2 = data2["price_usd"]
X2 = data2.drop(["price_usd"], axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3, random_state=42)

In [ ]:
reg = DecisionTreeRegressor(max_depth=3)
reg.fit(X2_train, y2_train)

DecisionTreeRegressor(max_depth=3)

In [ ]:
pred2 = reg.predict(X2_test)
print(pred2)

[ 7860.55622081  7522.55544589 13322.45659846 ...  1781.61287731
  1781.61287731  3354.80428196]

In [ ]:
print(reg.score(X2_test, y2_test))

0.6961813414693969

In [ ]:
text_representation = tree.export_text(reg)
print(text_representation)

NameError: ignored

##Задание 2

BaggingClassifier

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC

In [ ]:
clf_bagging = BaggingClassifier(estimator=LogisticRegression(), n_estimators=100, random_state=0).fit(X1_train, y1_train)

print(clf_bagging.score(X1_test, y1_test))

0.736197550692632

In [ ]:
pred3 = clf_bagging.predict(X1_test)
print(pred3)

[1. 1. 0. ... 0. 0. 0.]

In [ ]:
import pickle
filename = 'model_2.h5'
pickle.dump(clf_bagging, open(filename, 'wb'))

BaggingRegressor

In [ ]:
from sklearn.ensemble import BaggingRegressor

In [ ]:
reg_bagging = BaggingRegressor(estimator= DecisionTreeRegressor(), n_estimators=100, random_state=0).fit(X2_train, y2_train)

In [ ]:
pred4 = reg_bagging.predict(X2_test)
print(pred4)

[ 7636.0922  5068.108  11087.7391 ...  1153.9258  2816.8933  2609.3469]

In [ ]:
print(reg_bagging.score(X2_test, y2_test))

0.9124921607651604

In [ ]:
import pickle
filename = 'model_2.h5'
pickle.dump(reg_bagging, open(filename, 'wb'))

GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf_boosting = GradientBoostingClassifier(n_estimators=100, learning_rate=0.001, max_depth=3, random_state=0).fit(X1_train, y1_train)

In [ ]:
print(clf_boosting.predict(X1_test))

[1. 1. 0. ... 0. 0. 0.]

In [ ]:
clf_boosting.score(X1_test, y1_test)

0.7245131499698856

GradientBoostingRegressor

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
reg_boosting = GradientBoostingRegressor(n_estimators=100, learning_rate=1.0, max_depth=3, random_state=0).fit(X2_train, y2_train)

In [ ]:
print(reg_boosting.predict(X2_test))

[ 6807.42006894  6001.11103885 11796.64760483 ...   860.89959752
  2342.1092197   2674.44158686]

In [ ]:
reg_boosting.score(X2_test, y2_test)

0.8926859086241904

StackingClassifier

In [ ]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier

estimators = [('rf', RandomForestClassifier(n_estimators=100, random_state=42)), ('dt', DecisionTreeClassifier())]
clf_stacking = StackingClassifier(estimators= estimators , final_estimator=LogisticRegression()).fit(X1_train, y1_train)

In [ ]:
clf_stacking.score(X1_test, y1_test)

0.7176604430167972

StackingRegressor

In [ ]:
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import RidgeCV
from sklearn.svm import LinearSVR

estimators = [('lr', RidgeCV()),('svr', LinearSVR(random_state=42))]
reg_stacking = StackingRegressor(estimators=estimators,final_estimator=RandomForestRegressor(n_estimators=10,random_state=42)).fit(X2_train, y2_train)

/usr/local/lib/python3.9/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [ ]:
reg_stacking.score(X2_test, y2_test)

0.7831177466777938

##Задание 3

классификация

In [ ]:
from xgboost import XGBClassifier

bst = XGBClassifier(n_estimators=100, max_depth=3, learning_rate=1, objective='binary:logistic').fit(X1_train, y1_train)

In [ ]:
bst.predict(X1_test)

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
bst.score(X1_test, y1_test)

0.7222779896941712

регрессия

In [ ]:
from xgboost import XGBRegressor

xgb = XGBRegressor(objective ='reg:linear', n_estimators = 100, max_depth=3, learning_rate=1).fit(X2_train, y2_train)

[10:16:56] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.

In [ ]:
xgb.predict(X2_test)

array([ 7223.4443,  6138.2886, 12067.118 , ...,  1374.5518,  2352.4448,
        3009.348 ], dtype=float32)

In [ ]:
xgb.score(X2_test, y2_test)

0.9065032413822904

##Задание 4

In [ ]:
from collections import Counter

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None,*,value=None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value

    def is_leaf_node(self):
        return self.value is not None


class DecisionTree:
    def __init__(self, min_samples_split=2, max_depth=100, n_features=None):
        self.min_samples_split=min_samples_split
        self.max_depth=max_depth
        self.n_features=n_features
        self.root=None

    def fit(self, X, y):
        self.n_features = X.shape[1] if not self.n_features else min(X.shape[1],self.n_features)
        self.root = self._grow_tree(X, y)
        return self

    def _grow_tree(self, X, y, depth=0):
        n_samples, n_feats = X.shape
        n_labels = len(np.unique(y))

        # check the stopping criteria
        if (depth>=self.max_depth or n_labels==1 or n_samples<self.min_samples_split):
            leaf_value = self._most_common_label(y)
            return Node(value=leaf_value)

        feat_idxs = np.random.choice(n_feats, self.n_features, replace=False)

        # find the best split
        best_feature, best_thresh = self._best_split(X, y, feat_idxs)

        # create child nodes
        left_idxs, right_idxs = self._split(X[:, best_feature], best_thresh)
        left = self._grow_tree(X[left_idxs, :], y.iloc[left_idxs], depth+1)
        right = self._grow_tree(X[right_idxs, :], y.iloc[right_idxs], depth+1)
        return Node(best_feature, best_thresh, left, right)


    def _best_split(self, X, y, feat_idxs):
        best_gain = -1
        split_idx, split_threshold = None, None

        for feat_idx in feat_idxs:
            X_column = X[:, feat_idx]
            thresholds = np.unique(X_column)

            for thr in thresholds:
                # calculate the information gain
                gain = self._information_gain(y, X_column, thr)

                if gain > best_gain:
                    best_gain = gain
                    split_idx = feat_idx
                    split_threshold = thr

        return split_idx, split_threshold


    def _information_gain(self, y, X_column, threshold):
        # parent entropy
        parent_entropy = self._entropy(y)

        # create children
        left_idxs, right_idxs = self._split(X_column, threshold)

        if len(left_idxs) == 0 or len(right_idxs) == 0:
            return 0

        # calculate the weighted avg. entropy of children
        n = len(y)
        n_l, n_r = len(left_idxs), len(right_idxs)
        e_l, e_r = self._entropy(y.iloc[left_idxs]), self._entropy(y.iloc[right_idxs])
        child_entropy = (n_l/n) * e_l + (n_r/n) * e_r

        # calculate the IG
        information_gain = parent_entropy - child_entropy
        return information_gain

    def _split(self, X_column, split_thresh):
        left_idxs = np.argwhere(X_column <= split_thresh).flatten()
        right_idxs = np.argwhere(X_column > split_thresh).flatten()
        return left_idxs, right_idxs

    def _entropy(self, y):
        hist = np.bincount(y)
        ps = hist / len(y)
        return -np.sum([p * np.log(p) for p in ps if p>0])


    def _most_common_label(self, y):
        counter = Counter(y)
        value = counter.most_common(1)[0][0]
        return value

    def predict(self, X):
        return np.array([self._traverse_tree(x, self.root) for x in X])

    def _traverse_tree(self, x, node):
        if node.is_leaf_node():
            return node.value

        if x[node.feature] <= node.threshold:
            return self._traverse_tree(x, node.left)
        return self._traverse_tree(x, node.right)

In [ ]:
clf = DecisionTree(max_depth=10).fit(X1_train, y1_train)
clf.predict(X1_test)

array([1., 1., 0., ..., 0., 0., 0.])